server:
  port: 28080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: STUDENT_APP

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driver-class-name: org.h2.Driver


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


